spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: aymane
    url: jdbc:mysql://localhost:3306/departement
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8082'